[package]
name = "sshear-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.4.0"
libsql-client = "0.33.2"
tokio = { version = "1.34.0", features = ["full"] }
chrono = "0.4.31"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
askama = "0.12.1"
askama_actix = "0.14.0"
